// -----------------------------------------------------------------------
// <auto-generated>
//   This code was generated by Pegasus 3.1.2.0
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
// </auto-generated>
// -----------------------------------------------------------------------

namespace
#line 1 "HandlebarsGrammar.peg"
           CompiledHandlebars.Compiler
#line default
{
    using System;
    using System.Collections.Generic;
    using Pegasus.Common;
    using
        #line 3 "HandlebarsGrammar.peg"
       CompiledHandlebars.Compiler.AST
        #line default
        ;
    using
        #line 4 "HandlebarsGrammar.peg"
       CompiledHandlebars.Compiler.AST.Expressions
        #line default
        ;
    using
        #line 6 "HandlebarsGrammar.peg"
       System.Linq
        #line default
        ;

    /// <summary>
    ///  Parses a string according to the rules of the <see cref="HbsParser" /> grammar.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Pegasus", "3.1.2.0")]
    public
    partial class
    #line 2 "HandlebarsGrammar.peg"
           HbsParser
    #line default
    {
        #line 8 "HandlebarsGrammar.peg"
 
    private static void AddError(string message, HandlebarsSyntaxErrorKind kind, Cursor state)
    {
        var existing = state["errors"] as IList<HandlebarsSyntaxError>;
        var newList = existing == null ? new List<HandlebarsSyntaxError>() : existing.ToList();
        newList.Add(new HandlebarsSyntaxError(        
            message,
            kind,
            state.Line,
            state.Column           
        ));
        state["errors"] = newList.AsReadOnly();
    }
        #line default

        /// <summary>
        ///  Parses a string according to the rules of the <see cref="HbsParser" /> grammar.
        /// </summary>
        /// <param name="subject">The parsing subject.</param>
        /// <param name="fileName">The optional file name to use in error messages.</param>
        /// <returns>The <see cref="HandlebarsTemplate" /> parsed from <paramref name="subject" />.</returns>
        /// <exception cref="FormatException">
        ///  Thrown when parsing fails against <paramref name="subject"/>.  The exception's <code>Data["cursor"]</code> will be set with the cursor where the fatal error occurred.
        /// </exception>
        public HandlebarsTemplate Parse(string subject, string fileName = null)
        {
            var cursor = new Cursor(subject, 0, fileName);
            var result = this.Template(ref cursor);
            if (result == null)
            {
                throw ExceptionHelper(cursor, state => "Failed to parse 'Template'.");
            }
            return result.Value;
        }

        private IParseResult<
            #line 23 "HandlebarsGrammar.peg"
         HandlebarsTemplate
            #line default
            > Template(ref Cursor cursor)
        {
            IParseResult<HandlebarsTemplate> r0 = null;
            var startCursor0 = cursor;
            IParseResult<MemberExpression> r1 = null;
            var modelStart = cursor;
            r1 = this.ModelNode(ref cursor);
            var modelEnd = cursor;
            var model = ValueOrDefault(r1);
            if (r1 != null)
            {
                IParseResult<IList<ASTElementBase>> r2 = null;
                var itemsStart = cursor;
                r2 = this.Element(ref cursor);
                var itemsEnd = cursor;
                var items = ValueOrDefault(r2);
                if (r2 != null)
                {
                    IParseResult<string> r3 = null;
                    r3 = this.EOF(ref cursor);
                    if (r3 != null)
                    {
                        r0 = this.ReturnHelper<HandlebarsTemplate>(startCursor0, ref cursor, state =>
                            #line 24 "HandlebarsGrammar.peg"
                                         new HandlebarsTemplate(items, model, state["errors"] as IList<HandlebarsSyntaxError>)
                            #line default
                            );
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<
            #line 26 "HandlebarsGrammar.peg"
           MemberExpression
            #line default
            > ModelNode(ref Cursor cursor)
        {
            IParseResult<MemberExpression> r0 = null;
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<string> r1 = null;
                r1 = this.Opening(ref cursor);
                if (r1 != null)
                {
                    IParseResult<string> r2 = null;
                    r2 = this.ModelKeyword(ref cursor);
                    if (r2 != null)
                    {
                        IParseResult<MemberExpression> r3 = null;
                        var valueStart = cursor;
                        r3 = this.MemberExpression(ref cursor);
                        var valueEnd = cursor;
                        var value = ValueOrDefault(r3);
                        if (r3 != null)
                        {
                            IParseResult<string> r4 = null;
                            r4 = this.Closing(ref cursor);
                            if (r4 != null)
                            {
                                r0 = this.ReturnHelper<MemberExpression>(startCursor0, ref cursor, state =>
                                    #line 27 "HandlebarsGrammar.peg"
                                                            value
                                    #line default
                                    );
                            }
                            else
                            {
                                cursor = startCursor0;
                            }
                        }
                        else
                        {
                            cursor = startCursor0;
                        }
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            if (r0 == null)
            {
                var startCursor1 = cursor;
                IParseResult<string> r5 = null;
                var vStart = cursor;
                r5 = this.Opening(ref cursor);
                var vEnd = cursor;
                var v = ValueOrDefault(r5);
                if (r5 != null)
                {
                    IParseResult<string> r6 = null;
                    r6 = this.ModelKeyword(ref cursor);
                    if (r6 != null)
                    {
                        IParseResult<IList<string>> r7 = null;
                        var startCursor2 = cursor;
                        var l0 = new List<string>();
                        while (true)
                        {
                            IParseResult<string> r8 = null;
                            var startCursor3 = cursor;
                            IParseResult<string> r9 = null;
                            var startCursor4 = cursor;
                            IParseResult<string> r10 = null;
                            r10 = this.Closing(ref cursor);
                            if (r10 == null)
                            {
                                r9 = this.ReturnHelper<string>(cursor, ref cursor, state => string.Empty);
                            }
                            else
                            {
                                cursor = startCursor4;
                            }
                            if (r9 != null)
                            {
                                IParseResult<string> r11 = null;
                                r11 = this.ParseAny(ref cursor);
                                if (r11 != null)
                                {
                                    {
                                        var len = cursor.Location - startCursor3.Location;
                                        r8 = this.ReturnHelper<string>(startCursor3, ref cursor, state =>
                                            state.Subject.Substring(startCursor3.Location, len)
                                            );
                                    }
                                }
                                else
                                {
                                    cursor = startCursor3;
                                }
                            }
                            else
                            {
                                cursor = startCursor3;
                            }
                            if (r8 != null)
                            {
                                l0.Add(r8.Value);
                            }
                            else
                            {
                                break;
                            }
                        }
                        r7 = this.ReturnHelper<IList<string>>(startCursor2, ref cursor, state => l0.AsReadOnly());
                        if (r7 != null)
                        {
                            IParseResult<string> r12 = null;
                            r12 = this.Closing(ref cursor);
                            if (r12 != null)
                            {
                                IParseResult<string> r13 = null;
                                var startCursor5 = cursor;
                                {
                                    var state = cursor.WithMutability(mutable: true);
                                    #line 28 "HandlebarsGrammar.peg"
                                                           AddError("Malformed ModelToken. Syntax is: {{model MemberExpression}}", HandlebarsSyntaxErrorKind.MalformedModelToken, state);
                                    #line default
                                    cursor = state.WithMutability(mutable: false);
                                }
                                r13 = this.ReturnHelper<string>(startCursor5, ref cursor, state => null);
                                if (r13 != null)
                                {
                                    r0 = this.ReturnHelper<MemberExpression>(startCursor1, ref cursor, state =>
                                        #line 28 "HandlebarsGrammar.peg"
                                                                                                                                                                                              default(MemberExpression)
                                        #line default
                                        );
                                }
                                else
                                {
                                    cursor = startCursor1;
                                }
                            }
                            else
                            {
                                cursor = startCursor1;
                            }
                        }
                        else
                        {
                            cursor = startCursor1;
                        }
                    }
                    else
                    {
                        cursor = startCursor1;
                    }
                }
                else
                {
                    cursor = startCursor1;
                }
            }
            if (r0 == null)
            {
                var startCursor6 = cursor;
                IParseResult<IList<string>> r14 = null;
                var vStart = cursor;
                var startCursor7 = cursor;
                var l1 = new List<string>();
                while (true)
                {
                    IParseResult<string> r15 = null;
                    r15 = this.ParseAny(ref cursor);
                    if (r15 != null)
                    {
                        l1.Add(r15.Value);
                    }
                    else
                    {
                        break;
                    }
                }
                r14 = this.ReturnHelper<IList<string>>(startCursor7, ref cursor, state => l1.AsReadOnly());
                var vEnd = cursor;
                var v = ValueOrDefault(r14);
                if (r14 != null)
                {
                    IParseResult<string> r16 = null;
                    var startCursor8 = cursor;
                    {
                        var state = cursor.WithMutability(mutable: true);
                        #line 29 "HandlebarsGrammar.peg"
                   AddError("ModelToken is expected as first Token of a Handlebars-Template", HandlebarsSyntaxErrorKind.MissingModelToken, state);
                        #line default
                        cursor = state.WithMutability(mutable: false);
                    }
                    r16 = this.ReturnHelper<string>(startCursor8, ref cursor, state => null);
                    if (r16 != null)
                    {
                        r0 = this.ReturnHelper<MemberExpression>(startCursor6, ref cursor, state =>
                            #line 29 "HandlebarsGrammar.peg"
                                                                                                                                                       default(MemberExpression)
                            #line default
                            );
                    }
                    else
                    {
                        cursor = startCursor6;
                    }
                }
                else
                {
                    cursor = startCursor6;
                }
            }
            return r0;
        }

        private IParseResult<IList<ASTElementBase>> Element(ref Cursor cursor)
        {
            IParseResult<IList<ASTElementBase>> r0 = null;
            var startCursor0 = cursor;
            var l0 = new List<ASTElementBase>();
            while (true)
            {
                IParseResult<ASTElementBase> r1 = null;
                if (r1 == null)
                {
                    r1 = this.Comment(ref cursor);
                }
                if (r1 == null)
                {
                    r1 = this.Node(ref cursor);
                }
                if (r1 == null)
                {
                    r1 = this.Token(ref cursor);
                }
                if (r1 != null)
                {
                    l0.Add(r1.Value);
                }
                else
                {
                    break;
                }
            }
            r0 = this.ReturnHelper<IList<ASTElementBase>>(startCursor0, ref cursor, state => l0.AsReadOnly());
            return r0;
        }

        private IParseResult<
            #line 40 "HandlebarsGrammar.peg"
       ASTElementBase
            #line default
            > Token(ref Cursor cursor)
        {
            IParseResult<ASTElementBase> r0 = null;
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<string> r1 = null;
                r1 = this.ParseLiteral(ref cursor, "{{");
                if (r1 != null)
                {
                    IParseResult<ASTElementBase> r2 = null;
                    var valueStart = cursor;
                    r2 = this.ASTLeaf(ref cursor);
                    var valueEnd = cursor;
                    var value = ValueOrDefault(r2);
                    if (r2 != null)
                    {
                        IParseResult<string> r3 = null;
                        r3 = this.ParseLiteral(ref cursor, "}}");
                        if (r3 != null)
                        {
                            r0 = this.ReturnHelper<ASTElementBase>(startCursor0, ref cursor, state =>
                                #line 41 "HandlebarsGrammar.peg"
                                {value.SetTokenType(TokenType.Encoded); return value;}
                                #line default
                                );
                        }
                        else
                        {
                            cursor = startCursor0;
                        }
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            if (r0 == null)
            {
                var startCursor1 = cursor;
                IParseResult<string> r4 = null;
                r4 = this.ParseLiteral(ref cursor, "{{{");
                if (r4 != null)
                {
                    IParseResult<ASTElementBase> r5 = null;
                    var valueStart = cursor;
                    r5 = this.ASTLeaf(ref cursor);
                    var valueEnd = cursor;
                    var value = ValueOrDefault(r5);
                    if (r5 != null)
                    {
                        IParseResult<string> r6 = null;
                        r6 = this.ParseLiteral(ref cursor, "}}}");
                        if (r6 != null)
                        {
                            r0 = this.ReturnHelper<ASTElementBase>(startCursor1, ref cursor, state =>
                                #line 42 "HandlebarsGrammar.peg"
                                  {value.SetTokenType(TokenType.Escaped); return value;}
                                #line default
                                );
                        }
                        else
                        {
                            cursor = startCursor1;
                        }
                    }
                    else
                    {
                        cursor = startCursor1;
                    }
                }
                else
                {
                    cursor = startCursor1;
                }
            }
            if (r0 == null)
            {
                r0 = this.MarkupLiteral(ref cursor);
            }
            return r0;
        }

        private IParseResult<
            #line 45 "HandlebarsGrammar.peg"
         ASTElementBase
            #line default
            > ASTLeaf(ref Cursor cursor)
        {
            IParseResult<ASTElementBase> r0 = null;
            r0 = this.YieldStatement(ref cursor);
            return r0;
        }

        private IParseResult<
            #line 49 "HandlebarsGrammar.peg"
                YieldStatement
            #line default
            > YieldStatement(ref Cursor cursor)
        {
            IParseResult<YieldStatement> r0 = null;
            var startCursor0 = cursor;
            IParseResult<MemberExpression> r1 = null;
            var valStart = cursor;
            r1 = this.MemberExpression(ref cursor);
            var valEnd = cursor;
            var val = ValueOrDefault(r1);
            if (r1 != null)
            {
                r0 = this.ReturnHelper<YieldStatement>(startCursor0, ref cursor, state =>
                    #line 50 "HandlebarsGrammar.peg"
                            new YieldStatement(val,valStart.Line,valStart.Column)
                    #line default
                    );
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<
            #line 52 "HandlebarsGrammar.peg"
               MarkupLiteral
            #line default
            > MarkupLiteral(ref Cursor cursor)
        {
            IParseResult<MarkupLiteral> r0 = null;
            var startCursor0 = cursor;
            IParseResult<IList<string>> r1 = null;
            var valueStart = cursor;
            var startCursor1 = cursor;
            var l0 = new List<string>();
            while (true)
            {
                IParseResult<string> r2 = null;
                var startCursor2 = cursor;
                IParseResult<string> r3 = null;
                var startCursor3 = cursor;
                IParseResult<string> r4 = null;
                r4 = this.Opening(ref cursor);
                if (r4 == null)
                {
                    r3 = this.ReturnHelper<string>(cursor, ref cursor, state => string.Empty);
                }
                else
                {
                    cursor = startCursor3;
                }
                if (r3 != null)
                {
                    IParseResult<string> r5 = null;
                    var startCursor4 = cursor;
                    IParseResult<string> r6 = null;
                    r6 = this.Closing(ref cursor);
                    if (r6 == null)
                    {
                        r5 = this.ReturnHelper<string>(cursor, ref cursor, state => string.Empty);
                    }
                    else
                    {
                        cursor = startCursor4;
                    }
                    if (r5 != null)
                    {
                        IParseResult<string> r7 = null;
                        r7 = this.ParseAny(ref cursor);
                        if (r7 != null)
                        {
                            {
                                var len = cursor.Location - startCursor2.Location;
                                r2 = this.ReturnHelper<string>(startCursor2, ref cursor, state =>
                                    state.Subject.Substring(startCursor2.Location, len)
                                    );
                            }
                        }
                        else
                        {
                            cursor = startCursor2;
                        }
                    }
                    else
                    {
                        cursor = startCursor2;
                    }
                }
                else
                {
                    cursor = startCursor2;
                }
                if (r2 != null)
                {
                    l0.Add(r2.Value);
                }
                else
                {
                    break;
                }
            }
            if (l0.Count >= 1)
            {
                r1 = this.ReturnHelper<IList<string>>(startCursor1, ref cursor, state => l0.AsReadOnly());
            }
            else
            {
                cursor = startCursor1;
            }
            var valueEnd = cursor;
            var value = ValueOrDefault(r1);
            if (r1 != null)
            {
                r0 = this.ReturnHelper<MarkupLiteral>(startCursor0, ref cursor, state =>
                    #line 53 "HandlebarsGrammar.peg"
                                       new MarkupLiteral(string.Concat(value), valueStart.Line, valueStart.Column)
                    #line default
                    );
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<
            #line 55 "HandlebarsGrammar.peg"
         ASTElementBase
            #line default
            > Comment(ref Cursor cursor)
        {
            IParseResult<ASTElementBase> r0 = null;
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<string> r1 = null;
                r1 = this.MultilineCommentOpening(ref cursor);
                if (r1 != null)
                {
                    IParseResult<IList<string>> r2 = null;
                    var valStart = cursor;
                    var startCursor1 = cursor;
                    var l0 = new List<string>();
                    while (true)
                    {
                        IParseResult<string> r3 = null;
                        var startCursor2 = cursor;
                        IParseResult<string> r4 = null;
                        var startCursor3 = cursor;
                        IParseResult<string> r5 = null;
                        r5 = this.MultilineCommentClosing(ref cursor);
                        if (r5 == null)
                        {
                            r4 = this.ReturnHelper<string>(cursor, ref cursor, state => string.Empty);
                        }
                        else
                        {
                            cursor = startCursor3;
                        }
                        if (r4 != null)
                        {
                            IParseResult<string> r6 = null;
                            r6 = this.ParseAny(ref cursor);
                            if (r6 != null)
                            {
                                {
                                    var len = cursor.Location - startCursor2.Location;
                                    r3 = this.ReturnHelper<string>(startCursor2, ref cursor, state =>
                                        state.Subject.Substring(startCursor2.Location, len)
                                        );
                                }
                            }
                            else
                            {
                                cursor = startCursor2;
                            }
                        }
                        else
                        {
                            cursor = startCursor2;
                        }
                        if (r3 != null)
                        {
                            l0.Add(r3.Value);
                        }
                        else
                        {
                            break;
                        }
                    }
                    r2 = this.ReturnHelper<IList<string>>(startCursor1, ref cursor, state => l0.AsReadOnly());
                    var valEnd = cursor;
                    var val = ValueOrDefault(r2);
                    if (r2 != null)
                    {
                        IParseResult<string> r7 = null;
                        r7 = this.MultilineCommentClosing(ref cursor);
                        if (r7 != null)
                        {
                            r0 = this.ReturnHelper<ASTElementBase>(startCursor0, ref cursor, state =>
                                #line 56 "HandlebarsGrammar.peg"
                                                                                          new CommentLiteral(CommentType.Multi, string.Concat(val), valStart.Line, valStart.Column)
                                #line default
                                );
                        }
                        else
                        {
                            cursor = startCursor0;
                        }
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            if (r0 == null)
            {
                var startCursor4 = cursor;
                IParseResult<string> r8 = null;
                r8 = this.CommentOpening(ref cursor);
                if (r8 != null)
                {
                    IParseResult<IList<string>> r9 = null;
                    var valStart = cursor;
                    var startCursor5 = cursor;
                    var l1 = new List<string>();
                    while (true)
                    {
                        IParseResult<string> r10 = null;
                        var startCursor6 = cursor;
                        IParseResult<string> r11 = null;
                        var startCursor7 = cursor;
                        IParseResult<string> r12 = null;
                        r12 = this.CommentClosing(ref cursor);
                        if (r12 == null)
                        {
                            r11 = this.ReturnHelper<string>(cursor, ref cursor, state => string.Empty);
                        }
                        else
                        {
                            cursor = startCursor7;
                        }
                        if (r11 != null)
                        {
                            IParseResult<string> r13 = null;
                            r13 = this.ParseAny(ref cursor);
                            if (r13 != null)
                            {
                                {
                                    var len = cursor.Location - startCursor6.Location;
                                    r10 = this.ReturnHelper<string>(startCursor6, ref cursor, state =>
                                        state.Subject.Substring(startCursor6.Location, len)
                                        );
                                }
                            }
                            else
                            {
                                cursor = startCursor6;
                            }
                        }
                        else
                        {
                            cursor = startCursor6;
                        }
                        if (r10 != null)
                        {
                            l1.Add(r10.Value);
                        }
                        else
                        {
                            break;
                        }
                    }
                    r9 = this.ReturnHelper<IList<string>>(startCursor5, ref cursor, state => l1.AsReadOnly());
                    var valEnd = cursor;
                    var val = ValueOrDefault(r9);
                    if (r9 != null)
                    {
                        IParseResult<string> r14 = null;
                        r14 = this.CommentClosing(ref cursor);
                        if (r14 != null)
                        {
                            r0 = this.ReturnHelper<ASTElementBase>(startCursor4, ref cursor, state =>
                                #line 57 "HandlebarsGrammar.peg"
                                                               new CommentLiteral(CommentType.Single, string.Concat(val), valStart.Line, valStart.Column)
                                #line default
                                );
                        }
                        else
                        {
                            cursor = startCursor4;
                        }
                    }
                    else
                    {
                        cursor = startCursor4;
                    }
                }
                else
                {
                    cursor = startCursor4;
                }
            }
            return r0;
        }

        private IParseResult<
            #line 63 "HandlebarsGrammar.peg"
      ASTElementBase
            #line default
            > Node(ref Cursor cursor)
        {
            IParseResult<ASTElementBase> r0 = null;
            if (r0 == null)
            {
                r0 = this.WithBlock(ref cursor);
            }
            if (r0 == null)
            {
                r0 = this.IfBlock(ref cursor);
            }
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<string> r1 = null;
                r1 = this.Opening(ref cursor);
                if (r1 != null)
                {
                    IParseResult<string> r2 = null;
                    r2 = this.BlockOpeningIdentifier(ref cursor);
                    if (r2 != null)
                    {
                        IParseResult<IList<string>> r3 = null;
                        var nameStart = cursor;
                        var startCursor1 = cursor;
                        var l0 = new List<string>();
                        while (true)
                        {
                            IParseResult<string> r4 = null;
                            var startCursor2 = cursor;
                            IParseResult<string> r5 = null;
                            var startCursor3 = cursor;
                            IParseResult<string> r6 = null;
                            r6 = this.Closing(ref cursor);
                            if (r6 == null)
                            {
                                r5 = this.ReturnHelper<string>(cursor, ref cursor, state => string.Empty);
                            }
                            else
                            {
                                cursor = startCursor3;
                            }
                            if (r5 != null)
                            {
                                IParseResult<string> r7 = null;
                                r7 = this.ParseAny(ref cursor);
                                if (r7 != null)
                                {
                                    {
                                        var len = cursor.Location - startCursor2.Location;
                                        r4 = this.ReturnHelper<string>(startCursor2, ref cursor, state =>
                                            state.Subject.Substring(startCursor2.Location, len)
                                            );
                                    }
                                }
                                else
                                {
                                    cursor = startCursor2;
                                }
                            }
                            else
                            {
                                cursor = startCursor2;
                            }
                            if (r4 != null)
                            {
                                l0.Add(r4.Value);
                            }
                            else
                            {
                                break;
                            }
                        }
                        if (l0.Count >= 1)
                        {
                            r3 = this.ReturnHelper<IList<string>>(startCursor1, ref cursor, state => l0.AsReadOnly());
                        }
                        else
                        {
                            cursor = startCursor1;
                        }
                        var nameEnd = cursor;
                        var name = ValueOrDefault(r3);
                        if (r3 != null)
                        {
                            IParseResult<string> r8 = null;
                            r8 = this.Closing(ref cursor);
                            if (r8 != null)
                            {
                                IParseResult<string> r9 = null;
                                var startCursor4 = cursor;
                                {
                                    var state = cursor.WithMutability(mutable: true);
                                    #line 66 "HandlebarsGrammar.peg"
                                                                        AddError(string.Format("Unknown Block Token '{0}'!",name), HandlebarsSyntaxErrorKind.UnknownBlock, state);
                                    #line default
                                    cursor = state.WithMutability(mutable: false);
                                }
                                r9 = this.ReturnHelper<string>(startCursor4, ref cursor, state => null);
                                if (r9 != null)
                                {
                                    r0 = this.ReturnHelper<ASTElementBase>(startCursor0, ref cursor, state =>
                                        #line 66 "HandlebarsGrammar.peg"
                                                                                                                                                                                      new MarkupLiteral(null,0,0)
                                        #line default
                                        );
                                }
                                else
                                {
                                    cursor = startCursor0;
                                }
                            }
                            else
                            {
                                cursor = startCursor0;
                            }
                        }
                        else
                        {
                            cursor = startCursor0;
                        }
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            return r0;
        }

        private IParseResult<IList<ASTElementBase>> BlockBody(ref Cursor cursor)
        {
            IParseResult<IList<ASTElementBase>> r0 = null;
            r0 = this.Element(ref cursor);
            return r0;
        }

        private IParseResult<
            #line 74 "HandlebarsGrammar.peg"
           WithBlock
            #line default
            > WithBlock(ref Cursor cursor)
        {
            IParseResult<WithBlock> r0 = null;
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<MemberExpression> r1 = null;
                var memberStart = cursor;
                r1 = this.WithOpeningToken(ref cursor);
                var memberEnd = cursor;
                var member = ValueOrDefault(r1);
                if (r1 != null)
                {
                    IParseResult<IList<ASTElementBase>> r2 = null;
                    var bodyStart = cursor;
                    r2 = this.BlockBody(ref cursor);
                    var bodyEnd = cursor;
                    var body = ValueOrDefault(r2);
                    if (r2 != null)
                    {
                        IParseResult<string> r3 = null;
                        r3 = this.WithClosingToken(ref cursor);
                        if (r3 != null)
                        {
                            r0 = this.ReturnHelper<WithBlock>(startCursor0, ref cursor, state =>
                                #line 75 "HandlebarsGrammar.peg"
                                                                new WithBlock(member, body, memberStart.Line, memberStart.Column )
                                #line default
                                );
                        }
                        else
                        {
                            cursor = startCursor0;
                        }
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            if (r0 == null)
            {
                var startCursor1 = cursor;
                IParseResult<MemberExpression> r4 = null;
                var memberStart = cursor;
                r4 = this.WithOpeningToken(ref cursor);
                var memberEnd = cursor;
                var member = ValueOrDefault(r4);
                if (r4 != null)
                {
                    IParseResult<IList<ASTElementBase>> r5 = null;
                    var bodyStart = cursor;
                    r5 = this.BlockBody(ref cursor);
                    var bodyEnd = cursor;
                    var body = ValueOrDefault(r5);
                    if (r5 != null)
                    {
                        IParseResult<string> r6 = null;
                        var startCursor2 = cursor;
                        {
                            var state = cursor.WithMutability(mutable: true);
                            #line 76 "HandlebarsGrammar.peg"
                                                     AddError("Missing '{{/with}}' for {{#with}}", HandlebarsSyntaxErrorKind.MalformedBlock, state);
                            #line default
                            cursor = state.WithMutability(mutable: false);
                        }
                        r6 = this.ReturnHelper<string>(startCursor2, ref cursor, state => null);
                        if (r6 != null)
                        {
                            r0 = this.ReturnHelper<WithBlock>(startCursor1, ref cursor, state =>
                                #line 76 "HandlebarsGrammar.peg"
                                                                                                                                                         new WithBlock(null, null, 0, 0)
                                #line default
                                );
                        }
                        else
                        {
                            cursor = startCursor1;
                        }
                    }
                    else
                    {
                        cursor = startCursor1;
                    }
                }
                else
                {
                    cursor = startCursor1;
                }
            }
            return r0;
        }

        private IParseResult<
            #line 78 "HandlebarsGrammar.peg"
                  MemberExpression
            #line default
            > WithOpeningToken(ref Cursor cursor)
        {
            IParseResult<MemberExpression> r0 = null;
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<string> r1 = null;
                r1 = this.ParseLiteral(ref cursor, "{{");
                if (r1 != null)
                {
                    IParseResult<string> r2 = null;
                    r2 = this.BlockOpeningIdentifier(ref cursor);
                    if (r2 != null)
                    {
                        IParseResult<string> r3 = null;
                        r3 = this.WithKeyword(ref cursor);
                        if (r3 != null)
                        {
                            IParseResult<MemberExpression> r4 = null;
                            var valStart = cursor;
                            r4 = this.MemberExpression(ref cursor);
                            var valEnd = cursor;
                            var val = ValueOrDefault(r4);
                            if (r4 != null)
                            {
                                IParseResult<string> r5 = null;
                                r5 = this.ParseLiteral(ref cursor, "}}");
                                if (r5 != null)
                                {
                                    r0 = this.ReturnHelper<MemberExpression>(startCursor0, ref cursor, state =>
                                        #line 79 "HandlebarsGrammar.peg"
                                                                          val
                                        #line default
                                        );
                                }
                                else
                                {
                                    cursor = startCursor0;
                                }
                            }
                            else
                            {
                                cursor = startCursor0;
                            }
                        }
                        else
                        {
                            cursor = startCursor0;
                        }
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            if (r0 == null)
            {
                var startCursor1 = cursor;
                IParseResult<string> r6 = null;
                r6 = this.ParseLiteral(ref cursor, "{{");
                if (r6 != null)
                {
                    IParseResult<string> r7 = null;
                    r7 = this.BlockOpeningIdentifier(ref cursor);
                    if (r7 != null)
                    {
                        IParseResult<string> r8 = null;
                        r8 = this.WithKeyword(ref cursor);
                        if (r8 != null)
                        {
                            IParseResult<IList<string>> r9 = null;
                            var vStart = cursor;
                            var startCursor2 = cursor;
                            var l0 = new List<string>();
                            while (true)
                            {
                                IParseResult<string> r10 = null;
                                var startCursor3 = cursor;
                                IParseResult<string> r11 = null;
                                var startCursor4 = cursor;
                                IParseResult<string> r12 = null;
                                r12 = this.Closing(ref cursor);
                                if (r12 == null)
                                {
                                    r11 = this.ReturnHelper<string>(cursor, ref cursor, state => string.Empty);
                                }
                                else
                                {
                                    cursor = startCursor4;
                                }
                                if (r11 != null)
                                {
                                    IParseResult<string> r13 = null;
                                    r13 = this.ParseAny(ref cursor);
                                    if (r13 != null)
                                    {
                                        {
                                            var len = cursor.Location - startCursor3.Location;
                                            r10 = this.ReturnHelper<string>(startCursor3, ref cursor, state =>
                                                state.Subject.Substring(startCursor3.Location, len)
                                                );
                                        }
                                    }
                                    else
                                    {
                                        cursor = startCursor3;
                                    }
                                }
                                else
                                {
                                    cursor = startCursor3;
                                }
                                if (r10 != null)
                                {
                                    l0.Add(r10.Value);
                                }
                                else
                                {
                                    break;
                                }
                            }
                            r9 = this.ReturnHelper<IList<string>>(startCursor2, ref cursor, state => l0.AsReadOnly());
                            var vEnd = cursor;
                            var v = ValueOrDefault(r9);
                            if (r9 != null)
                            {
                                IParseResult<string> r14 = null;
                                r14 = this.ParseLiteral(ref cursor, "}}");
                                if (r14 != null)
                                {
                                    IParseResult<string> r15 = null;
                                    var startCursor5 = cursor;
                                    {
                                        var state = cursor.WithMutability(mutable: true);
                                        #line 80 "HandlebarsGrammar.peg"
                                                                           AddError("Missing MemberExpression in #with Token. Syntax: {{#with MemberExpression}}", HandlebarsSyntaxErrorKind.MissingMemberExpression, state );
                                        #line default
                                        cursor = state.WithMutability(mutable: false);
                                    }
                                    r15 = this.ReturnHelper<string>(startCursor5, ref cursor, state => null);
                                    if (r15 != null)
                                    {
                                        r0 = this.ReturnHelper<MemberExpression>(startCursor1, ref cursor, state =>
                                            #line 80 "HandlebarsGrammar.peg"
                                                                                                                                                                                                                                   new MemberExpression(null)
                                            #line default
                                            );
                                    }
                                    else
                                    {
                                        cursor = startCursor1;
                                    }
                                }
                                else
                                {
                                    cursor = startCursor1;
                                }
                            }
                            else
                            {
                                cursor = startCursor1;
                            }
                        }
                        else
                        {
                            cursor = startCursor1;
                        }
                    }
                    else
                    {
                        cursor = startCursor1;
                    }
                }
                else
                {
                    cursor = startCursor1;
                }
            }
            return r0;
        }

        private IParseResult<string> WithClosingToken(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            r1 = this.ParseLiteral(ref cursor, "{{");
            if (r1 != null)
            {
                IParseResult<string> r2 = null;
                r2 = this.BlockClosingIdentifier(ref cursor);
                if (r2 != null)
                {
                    IParseResult<string> r3 = null;
                    r3 = this.WithKeyword(ref cursor);
                    if (r3 != null)
                    {
                        IParseResult<string> r4 = null;
                        r4 = this.ParseLiteral(ref cursor, "}}");
                        if (r4 != null)
                        {
                            {
                                var len = cursor.Location - startCursor0.Location;
                                r0 = this.ReturnHelper<string>(startCursor0, ref cursor, state =>
                                    state.Subject.Substring(startCursor0.Location, len)
                                    );
                            }
                        }
                        else
                        {
                            cursor = startCursor0;
                        }
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<
            #line 87 "HandlebarsGrammar.peg"
         IfBlock
            #line default
            > IfBlock(ref Cursor cursor)
        {
            IParseResult<IfBlock> r0 = null;
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<MemberExpression> r1 = null;
                var memberStart = cursor;
                r1 = this.IfOpeningToken(ref cursor);
                var memberEnd = cursor;
                var member = ValueOrDefault(r1);
                if (r1 != null)
                {
                    IParseResult<IList<ASTElementBase>> r2 = null;
                    var bodyStart = cursor;
                    r2 = this.BlockBody(ref cursor);
                    var bodyEnd = cursor;
                    var body = ValueOrDefault(r2);
                    if (r2 != null)
                    {
                        IParseResult<string> r3 = null;
                        r3 = this.ElseToken(ref cursor);
                        if (r3 != null)
                        {
                            IParseResult<IList<ASTElementBase>> r4 = null;
                            var elseBlockStart = cursor;
                            r4 = this.BlockBody(ref cursor);
                            var elseBlockEnd = cursor;
                            var elseBlock = ValueOrDefault(r4);
                            if (r4 != null)
                            {
                                IParseResult<string> r5 = null;
                                r5 = this.IfClosingToken(ref cursor);
                                if (r5 != null)
                                {
                                    r0 = this.ReturnHelper<IfBlock>(startCursor0, ref cursor, state =>
                                        #line 88 "HandlebarsGrammar.peg"
                                                                                        new IfBlock(member, IfType.If, elseBlock, body, memberStart.Line, memberStart.Column)
                                        #line default
                                        );
                                }
                                else
                                {
                                    cursor = startCursor0;
                                }
                            }
                            else
                            {
                                cursor = startCursor0;
                            }
                        }
                        else
                        {
                            cursor = startCursor0;
                        }
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            if (r0 == null)
            {
                var startCursor1 = cursor;
                IParseResult<MemberExpression> r6 = null;
                var memberStart = cursor;
                r6 = this.UnlessOpeningToken(ref cursor);
                var memberEnd = cursor;
                var member = ValueOrDefault(r6);
                if (r6 != null)
                {
                    IParseResult<IList<ASTElementBase>> r7 = null;
                    var bodyStart = cursor;
                    r7 = this.BlockBody(ref cursor);
                    var bodyEnd = cursor;
                    var body = ValueOrDefault(r7);
                    if (r7 != null)
                    {
                        IParseResult<string> r8 = null;
                        r8 = this.ElseToken(ref cursor);
                        if (r8 != null)
                        {
                            IParseResult<IList<ASTElementBase>> r9 = null;
                            var elseBlockStart = cursor;
                            r9 = this.BlockBody(ref cursor);
                            var elseBlockEnd = cursor;
                            var elseBlock = ValueOrDefault(r9);
                            if (r9 != null)
                            {
                                IParseResult<string> r10 = null;
                                r10 = this.UnlessClosingToken(ref cursor);
                                if (r10 != null)
                                {
                                    r0 = this.ReturnHelper<IfBlock>(startCursor1, ref cursor, state =>
                                        #line 89 "HandlebarsGrammar.peg"
                                                                                                new IfBlock(member, IfType.Unless, elseBlock, body, memberStart.Line, memberStart.Column)
                                        #line default
                                        );
                                }
                                else
                                {
                                    cursor = startCursor1;
                                }
                            }
                            else
                            {
                                cursor = startCursor1;
                            }
                        }
                        else
                        {
                            cursor = startCursor1;
                        }
                    }
                    else
                    {
                        cursor = startCursor1;
                    }
                }
                else
                {
                    cursor = startCursor1;
                }
            }
            if (r0 == null)
            {
                var startCursor2 = cursor;
                IParseResult<MemberExpression> r11 = null;
                var memberStart = cursor;
                r11 = this.IfOpeningToken(ref cursor);
                var memberEnd = cursor;
                var member = ValueOrDefault(r11);
                if (r11 != null)
                {
                    IParseResult<IList<ASTElementBase>> r12 = null;
                    var bodyStart = cursor;
                    r12 = this.BlockBody(ref cursor);
                    var bodyEnd = cursor;
                    var body = ValueOrDefault(r12);
                    if (r12 != null)
                    {
                        IParseResult<string> r13 = null;
                        r13 = this.IfClosingToken(ref cursor);
                        if (r13 != null)
                        {
                            r0 = this.ReturnHelper<IfBlock>(startCursor2, ref cursor, state =>
                                #line 90 "HandlebarsGrammar.peg"
                                                          new IfBlock(member, IfType.If, body, memberStart.Line, memberStart.Column)
                                #line default
                                );
                        }
                        else
                        {
                            cursor = startCursor2;
                        }
                    }
                    else
                    {
                        cursor = startCursor2;
                    }
                }
                else
                {
                    cursor = startCursor2;
                }
            }
            if (r0 == null)
            {
                var startCursor3 = cursor;
                IParseResult<MemberExpression> r14 = null;
                var memberStart = cursor;
                r14 = this.UnlessOpeningToken(ref cursor);
                var memberEnd = cursor;
                var member = ValueOrDefault(r14);
                if (r14 != null)
                {
                    IParseResult<IList<ASTElementBase>> r15 = null;
                    var bodyStart = cursor;
                    r15 = this.BlockBody(ref cursor);
                    var bodyEnd = cursor;
                    var body = ValueOrDefault(r15);
                    if (r15 != null)
                    {
                        IParseResult<string> r16 = null;
                        r16 = this.UnlessClosingToken(ref cursor);
                        if (r16 != null)
                        {
                            r0 = this.ReturnHelper<IfBlock>(startCursor3, ref cursor, state =>
                                #line 91 "HandlebarsGrammar.peg"
                                                                  new IfBlock(member, IfType.Unless, body, memberStart.Line, memberStart.Column)
                                #line default
                                );
                        }
                        else
                        {
                            cursor = startCursor3;
                        }
                    }
                    else
                    {
                        cursor = startCursor3;
                    }
                }
                else
                {
                    cursor = startCursor3;
                }
            }
            return r0;
        }

        private IParseResult<
            #line 93 "HandlebarsGrammar.peg"
                MemberExpression
            #line default
            > IfOpeningToken(ref Cursor cursor)
        {
            IParseResult<MemberExpression> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            r1 = this.ParseLiteral(ref cursor, "{{");
            if (r1 != null)
            {
                IParseResult<string> r2 = null;
                r2 = this.BlockOpeningIdentifier(ref cursor);
                if (r2 != null)
                {
                    IParseResult<string> r3 = null;
                    r3 = this.IfKeyword(ref cursor);
                    if (r3 != null)
                    {
                        IParseResult<MemberExpression> r4 = null;
                        var memberStart = cursor;
                        r4 = this.MemberExpression(ref cursor);
                        var memberEnd = cursor;
                        var member = ValueOrDefault(r4);
                        if (r4 != null)
                        {
                            IParseResult<string> r5 = null;
                            r5 = this.ParseLiteral(ref cursor, "}}");
                            if (r5 != null)
                            {
                                r0 = this.ReturnHelper<MemberExpression>(startCursor0, ref cursor, state =>
                                    #line 94 "HandlebarsGrammar.peg"
                                                                         member
                                    #line default
                                    );
                            }
                            else
                            {
                                cursor = startCursor0;
                            }
                        }
                        else
                        {
                            cursor = startCursor0;
                        }
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<string> IfClosingToken(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            r1 = this.ParseLiteral(ref cursor, "{{");
            if (r1 != null)
            {
                IParseResult<string> r2 = null;
                r2 = this.BlockClosingIdentifier(ref cursor);
                if (r2 != null)
                {
                    IParseResult<string> r3 = null;
                    r3 = this.IfKeyword(ref cursor);
                    if (r3 != null)
                    {
                        IParseResult<string> r4 = null;
                        r4 = this.ParseLiteral(ref cursor, "}}");
                        if (r4 != null)
                        {
                            {
                                var len = cursor.Location - startCursor0.Location;
                                r0 = this.ReturnHelper<string>(startCursor0, ref cursor, state =>
                                    state.Subject.Substring(startCursor0.Location, len)
                                    );
                            }
                        }
                        else
                        {
                            cursor = startCursor0;
                        }
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<
            #line 99 "HandlebarsGrammar.peg"
                    MemberExpression
            #line default
            > UnlessOpeningToken(ref Cursor cursor)
        {
            IParseResult<MemberExpression> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            r1 = this.ParseLiteral(ref cursor, "{{");
            if (r1 != null)
            {
                IParseResult<string> r2 = null;
                r2 = this.BlockOpeningIdentifier(ref cursor);
                if (r2 != null)
                {
                    IParseResult<string> r3 = null;
                    r3 = this.UnlessKeyword(ref cursor);
                    if (r3 != null)
                    {
                        IParseResult<MemberExpression> r4 = null;
                        var memberStart = cursor;
                        r4 = this.MemberExpression(ref cursor);
                        var memberEnd = cursor;
                        var member = ValueOrDefault(r4);
                        if (r4 != null)
                        {
                            IParseResult<string> r5 = null;
                            r5 = this.ParseLiteral(ref cursor, "}}");
                            if (r5 != null)
                            {
                                r0 = this.ReturnHelper<MemberExpression>(startCursor0, ref cursor, state =>
                                    #line 100 "HandlebarsGrammar.peg"
                                                                             member
                                    #line default
                                    );
                            }
                            else
                            {
                                cursor = startCursor0;
                            }
                        }
                        else
                        {
                            cursor = startCursor0;
                        }
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<string> UnlessClosingToken(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            r1 = this.ParseLiteral(ref cursor, "{{");
            if (r1 != null)
            {
                IParseResult<string> r2 = null;
                r2 = this.BlockClosingIdentifier(ref cursor);
                if (r2 != null)
                {
                    IParseResult<string> r3 = null;
                    r3 = this.UnlessKeyword(ref cursor);
                    if (r3 != null)
                    {
                        IParseResult<string> r4 = null;
                        r4 = this.ParseLiteral(ref cursor, "}}");
                        if (r4 != null)
                        {
                            {
                                var len = cursor.Location - startCursor0.Location;
                                r0 = this.ReturnHelper<string>(startCursor0, ref cursor, state =>
                                    state.Subject.Substring(startCursor0.Location, len)
                                    );
                            }
                        }
                        else
                        {
                            cursor = startCursor0;
                        }
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<string> ElseToken(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            r1 = this.Opening(ref cursor);
            if (r1 != null)
            {
                IParseResult<string> r2 = null;
                r2 = this.ElseKeyword(ref cursor);
                if (r2 != null)
                {
                    IParseResult<string> r3 = null;
                    r3 = this.Closing(ref cursor);
                    if (r3 != null)
                    {
                        {
                            var len = cursor.Location - startCursor0.Location;
                            r0 = this.ReturnHelper<string>(startCursor0, ref cursor, state =>
                                state.Subject.Substring(startCursor0.Location, len)
                                );
                        }
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<
            #line 113 "HandlebarsGrammar.peg"
                  MemberExpression
            #line default
            > MemberExpression(ref Cursor cursor)
        {
            IParseResult<MemberExpression> r0 = null;
            var startCursor0 = cursor;
            IParseResult<IList<string>> r1 = null;
            r1 = this.Whitespace(ref cursor);
            if (r1 != null)
            {
                IParseResult<IdentifierElement> r2 = null;
                var valueStart = cursor;
                r2 = this.MemberPath(ref cursor);
                var valueEnd = cursor;
                var value = ValueOrDefault(r2);
                if (r2 != null)
                {
                    IParseResult<IList<string>> r3 = null;
                    r3 = this.Whitespace(ref cursor);
                    if (r3 != null)
                    {
                        r0 = this.ReturnHelper<MemberExpression>(startCursor0, ref cursor, state =>
                            #line 114 "HandlebarsGrammar.peg"
                                               new MemberExpression(value)
                            #line default
                            );
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<IdentifierElement> MemberPath(ref Cursor cursor)
        {
            IParseResult<IdentifierElement> r0 = null;
            if (r0 == null)
            {
                r0 = this.NestedMemberIdentifier(ref cursor);
            }
            if (r0 == null)
            {
                r0 = this.MemberIdentifier(ref cursor);
            }
            return r0;
        }

        private IParseResult<
            #line 121 "HandlebarsGrammar.peg"
                  IdentifierElement
            #line default
            > MemberIdentifier(ref Cursor cursor)
        {
            IParseResult<IdentifierElement> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            var valueStart = cursor;
            r1 = this.NameIdentifier(ref cursor);
            var valueEnd = cursor;
            var value = ValueOrDefault(r1);
            if (r1 != null)
            {
                r0 = this.ReturnHelper<IdentifierElement>(startCursor0, ref cursor, state =>
                    #line 122 "HandlebarsGrammar.peg"
                            new Identifier(value, null)
                    #line default
                    );
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<IdentifierElement> NestedMemberIdentifier(ref Cursor cursor)
        {
            IParseResult<IdentifierElement> r0 = null;
            if (r0 == null)
            {
                r0 = this.ParentContextName(ref cursor);
            }
            if (r0 == null)
            {
                r0 = this.ChildContextName(ref cursor);
            }
            return r0;
        }

        private IParseResult<
            #line 128 "HandlebarsGrammar.peg"
                   IdentifierElement
            #line default
            > ParentContextName(ref Cursor cursor)
        {
            IParseResult<IdentifierElement> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            r1 = this.ParentPathLiteral(ref cursor);
            if (r1 != null)
            {
                IParseResult<IdentifierElement> r2 = null;
                var nextStart = cursor;
                r2 = this.MemberPath(ref cursor);
                var nextEnd = cursor;
                var next = ValueOrDefault(r2);
                if (r2 != null)
                {
                    r0 = this.ReturnHelper<IdentifierElement>(startCursor0, ref cursor, state =>
                        #line 129 "HandlebarsGrammar.peg"
                                         new PathUp(next)
                        #line default
                        );
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<
            #line 131 "HandlebarsGrammar.peg"
                  IdentifierElement
            #line default
            > ChildContextName(ref Cursor cursor)
        {
            IParseResult<IdentifierElement> r0 = null;
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<string> r1 = null;
                var valueStart = cursor;
                r1 = this.NameIdentifier(ref cursor);
                var valueEnd = cursor;
                var value = ValueOrDefault(r1);
                if (r1 != null)
                {
                    IParseResult<string> r2 = null;
                    r2 = this.NameDelimiter(ref cursor);
                    if (r2 != null)
                    {
                        IParseResult<IdentifierElement> r3 = null;
                        var nextStart = cursor;
                        r3 = this.MemberPath(ref cursor);
                        var nextEnd = cursor;
                        var next = ValueOrDefault(r3);
                        if (r3 != null)
                        {
                            r0 = this.ReturnHelper<IdentifierElement>(startCursor0, ref cursor, state =>
                                #line 132 "HandlebarsGrammar.peg"
                                                          new Identifier(value, next)
                                #line default
                                );
                        }
                        else
                        {
                            cursor = startCursor0;
                        }
                    }
                    else
                    {
                        cursor = startCursor0;
                    }
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            if (r0 == null)
            {
                var startCursor1 = cursor;
                IParseResult<string> r4 = null;
                var valueStart = cursor;
                r4 = this.NameIdentifier(ref cursor);
                var valueEnd = cursor;
                var value = ValueOrDefault(r4);
                if (r4 != null)
                {
                    IParseResult<string> r5 = null;
                    r5 = this.NameDelimiter(ref cursor);
                    if (r5 != null)
                    {
                        IParseResult<IList<string>> r6 = null;
                        var startCursor2 = cursor;
                        var l0 = new List<string>();
                        while (true)
                        {
                            IParseResult<string> r7 = null;
                            r7 = this.NameDelimiter(ref cursor);
                            if (r7 != null)
                            {
                                l0.Add(r7.Value);
                            }
                            else
                            {
                                break;
                            }
                        }
                        if (l0.Count >= 1)
                        {
                            r6 = this.ReturnHelper<IList<string>>(startCursor2, ref cursor, state => l0.AsReadOnly());
                        }
                        else
                        {
                            cursor = startCursor2;
                        }
                        if (r6 != null)
                        {
                            IParseResult<IdentifierElement> r8 = null;
                            r8 = this.MemberPath(ref cursor);
                            if (r8 != null)
                            {
                                IParseResult<string> r9 = null;
                                var startCursor3 = cursor;
                                {
                                    var state = cursor.WithMutability(mutable: true);
                                    #line 133 "HandlebarsGrammar.peg"
                                                                             AddError("Malformed MemberExpression: multiple identifier delimiter!", HandlebarsSyntaxErrorKind.MalformedMemberExpression, state);
                                    #line default
                                    cursor = state.WithMutability(mutable: false);
                                }
                                r9 = this.ReturnHelper<string>(startCursor3, ref cursor, state => null);
                                if (r9 != null)
                                {
                                    r0 = this.ReturnHelper<IdentifierElement>(startCursor1, ref cursor, state =>
                                        #line 133 "HandlebarsGrammar.peg"
                                                                                                                                                                                                                    new Identifier(null, null)
                                        #line default
                                        );
                                }
                                else
                                {
                                    cursor = startCursor1;
                                }
                            }
                            else
                            {
                                cursor = startCursor1;
                            }
                        }
                        else
                        {
                            cursor = startCursor1;
                        }
                    }
                    else
                    {
                        cursor = startCursor1;
                    }
                }
                else
                {
                    cursor = startCursor1;
                }
            }
            if (r0 == null)
            {
                var startCursor4 = cursor;
                IParseResult<string> r10 = null;
                var valueStart = cursor;
                r10 = this.NameIdentifier(ref cursor);
                var valueEnd = cursor;
                var value = ValueOrDefault(r10);
                if (r10 != null)
                {
                    IParseResult<string> r11 = null;
                    r11 = this.NameDelimiter(ref cursor);
                    if (r11 != null)
                    {
                        IParseResult<string> r12 = null;
                        var startCursor5 = cursor;
                        {
                            var state = cursor.WithMutability(mutable: true);
                            #line 134 "HandlebarsGrammar.peg"
                                                 AddError("Malformed MemberExpression: identifier delimiter without subsequent identifier!", HandlebarsSyntaxErrorKind.MalformedMemberExpression,  state);
                            #line default
                            cursor = state.WithMutability(mutable: false);
                        }
                        r12 = this.ReturnHelper<string>(startCursor5, ref cursor, state => null);
                        if (r12 != null)
                        {
                            r0 = this.ReturnHelper<IdentifierElement>(startCursor4, ref cursor, state =>
                                #line 134 "HandlebarsGrammar.peg"
                                                                                                                                                                                                              new Identifier(null, null)
                                #line default
                                );
                        }
                        else
                        {
                            cursor = startCursor4;
                        }
                    }
                    else
                    {
                        cursor = startCursor4;
                    }
                }
                else
                {
                    cursor = startCursor4;
                }
            }
            return r0;
        }

        private IParseResult<
            #line 137 "HandlebarsGrammar.peg"
                string
            #line default
            > NameIdentifier(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            var startCursor0 = cursor;
            IParseResult<string> r1 = null;
            var startCursor1 = cursor;
            IParseResult<string> r2 = null;
            r2 = this.ReservedKeywords(ref cursor);
            if (r2 == null)
            {
                r1 = this.ReturnHelper<string>(cursor, ref cursor, state => string.Empty);
            }
            else
            {
                cursor = startCursor1;
            }
            if (r1 != null)
            {
                IParseResult<IList<string>> r3 = null;
                var valStart = cursor;
                r3 = this.Identifier(ref cursor);
                var valEnd = cursor;
                var val = ValueOrDefault(r3);
                if (r3 != null)
                {
                    r0 = this.ReturnHelper<string>(startCursor0, ref cursor, state =>
                        #line 138 "HandlebarsGrammar.peg"
                                          string.Concat(val)
                        #line default
                        );
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<IList<string>> Identifier(ref Cursor cursor)
        {
            IParseResult<IList<string>> r0 = null;
            var startCursor0 = cursor;
            var l0 = new List<string>();
            while (true)
            {
                IParseResult<string> r1 = null;
                if (r1 == null)
                {
                    r1 = this.ParseClass(ref cursor, "az", ignoreCase: true);
                }
                if (r1 == null)
                {
                    r1 = this.ParseClass(ref cursor, "09");
                }
                if (r1 == null)
                {
                    r1 = this.ParseLiteral(ref cursor, "_");
                }
                if (r1 != null)
                {
                    l0.Add(r1.Value);
                }
                else
                {
                    break;
                }
            }
            if (l0.Count >= 1)
            {
                r0 = this.ReturnHelper<IList<string>>(startCursor0, ref cursor, state => l0.AsReadOnly());
            }
            else
            {
                cursor = startCursor0;
            }
            return r0;
        }

        private IParseResult<string> ReservedKeywords(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            r0 = this.ElseKeyword(ref cursor);
            return r0;
        }

        private IParseResult<string> BlockOpeningIdentifier(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            r0 = this.ParseLiteral(ref cursor, "#");
            return r0;
        }

        private IParseResult<string> BlockClosingIdentifier(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            r0 = this.ParseLiteral(ref cursor, "/");
            return r0;
        }

        private IParseResult<string> WithKeyword(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            r0 = this.ParseLiteral(ref cursor, "with");
            return r0;
        }

        private IParseResult<string> IfKeyword(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            r0 = this.ParseLiteral(ref cursor, "if");
            return r0;
        }

        private IParseResult<string> UnlessKeyword(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            r0 = this.ParseLiteral(ref cursor, "unless");
            return r0;
        }

        private IParseResult<string> ElseKeyword(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            r0 = this.ParseLiteral(ref cursor, "else");
            return r0;
        }

        private IParseResult<string> ModelKeyword(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            r0 = this.ParseLiteral(ref cursor, "model");
            return r0;
        }

        private IParseResult<string> Opening(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "{{");
            }
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "{{{");
            }
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "{{{{");
            }
            return r0;
        }

        private IParseResult<string> Closing(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "}}");
            }
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "}}}");
            }
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "}}}}");
            }
            return r0;
        }

        private IParseResult<string> CommentOpening(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            r0 = this.ParseLiteral(ref cursor, "{{!");
            return r0;
        }

        private IParseResult<string> CommentClosing(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            r0 = this.ParseLiteral(ref cursor, "}}");
            return r0;
        }

        private IParseResult<string> MultilineCommentOpening(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            r0 = this.ParseLiteral(ref cursor, "{{!--");
            return r0;
        }

        private IParseResult<string> MultilineCommentClosing(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            r0 = this.ParseLiteral(ref cursor, "--}}");
            return r0;
        }

        private IParseResult<string> ParentPathLiteral(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            r0 = this.ParseLiteral(ref cursor, "../");
            return r0;
        }

        private IParseResult<string> NameDelimiter(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, ".");
            }
            if (r0 == null)
            {
                r0 = this.ParseLiteral(ref cursor, "/");
            }
            return r0;
        }

        private IParseResult<IList<string>> Whitespace(ref Cursor cursor)
        {
            IParseResult<IList<string>> r0 = null;
            var startCursor0 = cursor;
            var l0 = new List<string>();
            while (true)
            {
                IParseResult<string> r1 = null;
                r1 = this.ParseLiteral(ref cursor, " ");
                if (r1 != null)
                {
                    l0.Add(r1.Value);
                }
                else
                {
                    break;
                }
            }
            r0 = this.ReturnHelper<IList<string>>(startCursor0, ref cursor, state => l0.AsReadOnly());
            return r0;
        }

        private IParseResult<string> EOF(ref Cursor cursor)
        {
            IParseResult<string> r0 = null;
            if (r0 == null)
            {
                var startCursor0 = cursor;
                IParseResult<string> r1 = null;
                r1 = this.ParseAny(ref cursor);
                if (r1 == null)
                {
                    r0 = this.ReturnHelper<string>(cursor, ref cursor, state => string.Empty);
                }
                else
                {
                    cursor = startCursor0;
                }
            }
            if (r0 == null)
            {
                var cStart = cursor;
                r0 = this.ParseAny(ref cursor);
                var cEnd = cursor;
                var c = ValueOrDefault(r0);
            }
            return r0;
        }

        private IParseResult<string> ParseLiteral(ref Cursor cursor, string literal, bool ignoreCase = false)
        {
            if (cursor.Location + literal.Length <= cursor.Subject.Length)
            {
                var substr = cursor.Subject.Substring(cursor.Location, literal.Length);
                if (ignoreCase ? substr.Equals(literal, StringComparison.OrdinalIgnoreCase) : substr == literal)
                {
                    var endCursor = cursor.Advance(substr.Length);
                    var result = this.ReturnHelper<string>(cursor, ref endCursor, state => substr);
                    cursor = endCursor;
                    return result;
                }
            }
            return null;
        }

        private IParseResult<string> ParseClass(ref Cursor cursor, string characterRanges, bool negated = false, bool ignoreCase = false)
        {
            if (cursor.Location + 1 <= cursor.Subject.Length)
            {
                var c = cursor.Subject[cursor.Location];
                bool match = false;
                for (int i = 0; !match && i < characterRanges.Length; i += 2)
                {
                    match = c >= characterRanges[i] && c <= characterRanges[i + 1];
                }
                if (!match && ignoreCase && (char.IsUpper(c) || char.IsLower(c)))
                {
                    var cs = c.ToString();
                    for (int i = 0; !match && i < characterRanges.Length; i += 2)
                    {
                        var min = characterRanges[i];
                        var max = characterRanges[i + 1];
                        for (char o = min; !match && o <= max; o++)
                        {
                            match = (char.IsUpper(o) || char.IsLower(o)) && cs.Equals(o.ToString(), StringComparison.CurrentCultureIgnoreCase);
                        }
                    }
                }
                if (match ^ negated)
                {
                    var endCursor = cursor.Advance(1);
                    var substr = cursor.Subject.Substring(cursor.Location, 1);
                    var result = this.ReturnHelper<string>(cursor, ref endCursor, state => substr);
                    cursor = endCursor;
                    return result;
                }
            }
            return null;
        }

        private IParseResult<string> ParseAny(ref Cursor cursor)
        {
            if (cursor.Location + 1 <= cursor.Subject.Length)
            {
                var substr = cursor.Subject.Substring(cursor.Location, 1);
                var endCursor = cursor.Advance(1);
                var result = this.ReturnHelper<string>(cursor, ref endCursor, state => substr);
                cursor = endCursor;
                return result;
            }
            return null;
        }

        private IParseResult<T> ReturnHelper<T>(Cursor startCursor, ref Cursor endCursor, Func<Cursor, T> wrappedCode)
        {
            var result = wrappedCode(endCursor);
            var lexical = result as ILexical;
            if (lexical != null && lexical.StartCursor == null && lexical.EndCursor == null)
            {
                lexical.StartCursor = startCursor;
                lexical.EndCursor = endCursor;
            }
            return new ParseResult<T>(startCursor, endCursor, result);
        }

        private Exception ExceptionHelper(Cursor cursor, Func<Cursor, string> wrappedCode)
        {
            var ex = new FormatException(wrappedCode(cursor));
            ex.Data["cursor"] = cursor;
            return ex;
        }

        private T ValueOrDefault<T>(IParseResult<T> result)
        {
            return result == null
                ? default(T)
                : result.Value;
        }
    }
}
